# Postures
posture_home:
  "arm_left_1_joint": -0.87
  "arm_left_2_joint": 1.29
  "arm_left_3_joint": 2.34
  "arm_left_4_joint": 1.84
  "arm_left_5_joint": 1.31
  "arm_left_6_joint": -0.11
  "arm_left_7_joint": -1.20
  "arm_right_1_joint": -0.87
  "arm_right_2_joint": 1.29
  "arm_right_3_joint": 2.34
  "arm_right_4_joint": 1.84
  "arm_right_5_joint": 1.31
  "arm_right_6_joint": -0.11
  "arm_right_7_joint": -1.20
  "torso_lift_joint": 0.30

# EE targets
pre_open_dishwasher_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [0.2605, -0.6667, 0.7366]
    rotation: [0.7247, -0.01393, 0.01238, -0.6889]
    time: 8.0

pre_pull_dishwasher_drawer_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [0.05821, -0.6540, 0.7187]
    rotation: [-0.7166, 0.00178, 0.0336, 0.6967]
    time: 1.0

pre_pick_bowl_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [0.2173, -0.8442, 0.8346]
    rotation: [0.7294, -0.1777, -0.2184, -0.6235]
    time: 4.0

pre_close_dishwasher_drawer_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [-0.0121, -0.7282, 0.7150]
    rotation: [-0.7273, 0.0150, 0.0210, 0.6858]
    time: 10.0

# Demos
open_dishwasher_right:
  file: "open_dishwasher_right.npy"
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "orbbec_right/pose_tag_34"
  go_to_start_time: 4.0
  dt: 0.05
  gripper_controller: "gripper_right_controller"
  gripper_joints:
    - "gripper_right_left_finger_joint"
    - "gripper_right_right_finger_joint"
  gripper_max: 0.044
  gripper_min: 0.001

pull_dishwasher_drawer_right:
  file: "pull_dishwasher_drawer_right.npy"
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "orbbec_right/pose_tag_38"
  go_to_start_time: 4.0
  dt: 0.05
  gripper_controller: "gripper_right_controller"
  gripper_joints:
    - "gripper_right_left_finger_joint"
    - "gripper_right_right_finger_joint"
  gripper_max: 0.044
  gripper_min: 0.001

pick_bowl_right:
  file: "pick_bowl_right.npy"
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "orbbec_right/pose_tag_11"
  go_to_start_time: 4.0
  dt: 0.05
  gripper_controller: "gripper_right_controller"
  gripper_joints:
    - "gripper_right_left_finger_joint"
    - "gripper_right_right_finger_joint"
  gripper_max: 0.044
  gripper_min: 0.001

close_dishwasher_drawer_right:
  file: "close_dishwasher_drawer_right.npy"
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "orbbec_right/pose_tag_38"
  go_to_start_time: 4.0
  dt: 0.05
  gripper_controller: "gripper_right_controller"
  gripper_joints:
    - "gripper_right_left_finger_joint"
    - "gripper_right_right_finger_joint"
  gripper_max: 0.044
  gripper_min: 0.001

# Navigation goals
dishwasher:
  ref_frame: "orbbec_head/pose_tag_103"
  goal:
    translation: [1.169, -0.517, 0]
    rotation: [0, 0, 1, 0]
