left_waypoints:
  task: "gripper_left_grasping_frame"
  task_base_link: "base_link"
  ref_frame: "base_link"
  offset:
    translation:
      - [0.6693, 0.3481, 0.4492]
      - [0.5693, 0.3481, 0.4492]
    rotation:
      - [0.7296, -0.05501, 0.07221, 0.6778]
      - [0.7296, -0.05501, 0.07221, 0.6778]
    time:
      - 4.0
      - 8.0

right_waypoints:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  ref_frame: "base_link"
  offset:
    translation:
      - [0.6663, -0.3481, 0.4492]
      - [0.5663, -0.3481, 0.4492]
    rotation:
      - [-0.7296, -0.05501, -0.07221, 0.6778]
      - [-0.7296, -0.05501, -0.07221, 0.6778]
    time:
      - 4.0
      - 8.0

mobile_pose:
  task: "base_link"
  task_base_link: "world"
  ref_frame: "base_link"
  offset:
    translation: [1.0, 0, 0]
    rotation: [0, 0, 0.258819, 0.9659258]
    time: 10.0
