##################################################################
######################## GENERAL MOTIONS #########################
##################################################################

# Postures
posture_home_0:
  "arm_left_1_joint": -0.87
  "arm_left_2_joint": 1.29
  "arm_left_3_joint": 2.34
  "arm_left_4_joint": 1.84
  "arm_left_5_joint": 1.31
  "arm_left_6_joint": -0.11
  "arm_left_7_joint": -1.20
  "arm_right_1_joint": -0.87
  "arm_right_2_joint": 1.29
  "arm_right_3_joint": 2.34
  "arm_right_4_joint": 1.84
  "arm_right_5_joint": 1.31
  "arm_right_6_joint": -0.11
  "arm_right_7_joint": -1.20
  "torso_lift_joint": 0.30

posture_home:
  "arm_left_1_joint": -0.87
  "arm_left_2_joint": 1.29
  "arm_left_3_joint": 2.34
  "arm_left_4_joint": 1.84
  "arm_left_5_joint": 1.31
  "arm_left_6_joint": -0.11
  "arm_left_7_joint": -1.20
  "arm_right_1_joint": 1.31
  "arm_right_2_joint": -0.82
  "arm_right_3_joint": 2.92
  "arm_right_4_joint": 1.49
  "arm_right_5_joint": 1.41
  "arm_right_6_joint": -0.74
  "arm_right_7_joint": 1.48


##################################################################
####################### DISHWASHER MOTIONS #######################
##################################################################

# EE targets
pre_pick_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [0.595, -0.294, 0.730]
    rotation: [-0.563, 0.428, 0.478, 0.521]
    time: 4.0

over_mug_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "mug"
  offset:
    translation: [0.027, 0.043, 0.278]
    rotation: [-0.674, -0.052, 0.737, -0.005]
    time: 4.0

grasp_mug_right:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "mug"
  offset:
    translation: [0.025, 0.02, 0.09]
    rotation: [-0.674, -0.052, 0.737, -0.005]
    time: 4.0





    