posture_home:
  "arm_left_1_joint": -0.87
  "arm_left_2_joint": 1.29
  "arm_left_3_joint": 2.34
  "arm_left_4_joint": 1.84
  "arm_left_5_joint": 1.31
  "arm_left_6_joint": -0.11
  "arm_left_7_joint": -1.20
  "arm_right_1_joint": -0.87
  "arm_right_2_joint": 1.29
  "arm_right_3_joint": 2.34
  "arm_right_4_joint": 1.84
  "arm_right_5_joint": 1.31
  "arm_right_6_joint": -0.11
  "arm_right_7_joint": -1.20
  "torso_lift_joint": 0.30

pre_pick_from_table:
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "ci/base_link"
  offset:
    translation: [0.279, -0.326, 0.690]
    rotation: [-0.010, -0.012, 0.142, 0.990]
    time: 10.0

# Demos

demo_pick_mustard:
  file: "pick_mustard_right.npy"
  task: "gripper_right_grasping_frame"
  task_base_link: "base_link"
  base_link_frame: "ci/base_link"
  ref_frame: "orbbec_right/pose_tag_0"
  go_to_start_time: 4.0
  dt: 0.01
  gripper_controller: "gripper_right_controller"
  gripper_joints:
    - "gripper_right_left_finger_joint"
    - "gripper_right_right_finger_joint"
  gripper_max: 0.044
  gripper_min: 0.001

# GoTo offsets

table:
  ref_frame: "orbbec_head/pose_tag_104"
  goal:
    translation: [1.54, 0.44, 0]
    rotation: [0, 0, 1, 0]

mustard:
  ref_frame: "orbbec_right/pose_tag_0"
  goal:
    translation: [0.71, 0.045, 0]
    rotation: [0, 0, 1, 0]
