#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from states import MoveToTargetFromCfg, FollowWaypointsFromCfg
import numpy as np
import rospy
import rospkg
import smach
import tf2_ros


def main():
    rospy.init_node("smach_example_state_machine")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Create a SMACH state machine
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])

    # Define userdata for the state machine
    sm.userdata.client = client
    sm.userdata.tf_buffer = tf_buffer
    sm.userdata.config_path = rospack.get_path("fsm_cartesio") + "/config/dummy.yaml"
    sm.userdata.left_motion_tag = "left_waypoints"
    sm.userdata.right_motion_tag = "right_waypoints"
    sm.userdata.base_motion_tag = "mobile_pose"

    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "MOVE_LEFT",
            FollowWaypointsFromCfg(),
            transitions={"success": "MOVE_RIGHT", "fail": "fsm_fail"},
            remapping={
                "client": "client",
                "tf_prefix": "tf_prefix",
                "tf_buffer": "tf_buffer",
                "config_path": "config_path",
                "tag": "left_motion_tag",
            },
        )

        smach.StateMachine.add(
            "MOVE_RIGHT",
            FollowWaypointsFromCfg(),
            transitions={"success": "MOVE_BASE", "fail": "fsm_fail"},
            remapping={
                "client": "client",
                "tf_prefix": "tf_prefix",
                "tf_buffer": "tf_buffer",
                "config_path": "config_path",
                "tag": "right_motion_tag",
            },
        )

        smach.StateMachine.add(
            "MOVE_BASE",
            MoveToTargetFromCfg(),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
            remapping={
                "client": "client",
                "tf_prefix": "tf_prefix",
                "tf_buffer": "tf_buffer",
                "config_path": "config_path",
                "tag": "base_motion_tag",
            },
        )

    # Execute the state machine
    outcome = sm.execute()


if __name__ == "__main__":
    main()
