#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from states import (
    MoveToTargetFromCfg,
    FollowWaypointsFromCfg,
    PalGripperGrasp,
    PalGripperRelease,
    UpdateOdom,
    ChangeTaskControlMode,
    ChangeTaskBaseLink,
)
import numpy as np
import rospy
import rospkg
import smach
import tf2_ros


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Create a SMACH state machine
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])

    # Define userdata for the state machine
    sm.userdata.client = client
    sm.userdata.tf_buffer = tf_buffer
    sm.userdata.config_path = (
        rospack.get_path("fsm_cartesio") + "/config/open_door_with_left.yaml"
    )

    sm.userdata.left_home = "left_home"
    sm.userdata.right_camera_look_front = "right_camera_look_front"
    sm.userdata.base_go_to_door = "base_go_to_door"
    sm.userdata.left_go_to_handle = "left_go_to_handle"
    sm.userdata.left_turn_handle = "left_turn_handle"
    sm.userdata.left_go_back = "left_go_back"
    sm.userdata.base_go_back = "base_go_back"

    sm.userdata.parallel_gripper_controller = "parallel_gripper_left_controller"

    sm.userdata.base_task_name = "base_link"
    sm.userdata.ctrl_mode_velocity = "velocity"
    sm.userdata.ctrl_mode_position = "position"

    sm.userdata.left_task_name = "gripper_left_grasping_frame"
    sm.userdata.left_task_base_link = "base_link"

    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "INIT_ODOM",
            UpdateOdom(),
            transitions={"success": "LEFT_HOME_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_HOME_1",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_CAMERA_LOOK_FORWARD", "fail": "fsm_fail"},
            remapping={
                "tag": "left_home",
            },
        )
        smach.StateMachine.add(
            "RIGHT_CAMERA_LOOK_FORWARD",
            MoveToTargetFromCfg(),
            transitions={"success": "BASE_GO_TO_DOOR", "fail": "fsm_fail"},
            remapping={
                "tag": "right_camera_look_front",
            },
        )
        smach.StateMachine.add(
            "BASE_GO_TO_DOOR",
            MoveToTargetFromCfg(),
            transitions={"success": "UPDATE_ODOM_1", "fail": "fsm_fail"},
            remapping={
                "tag": "base_go_to_door",
            },
        )
        smach.StateMachine.add(
            "UPDATE_ODOM_1",
            UpdateOdom(),
            transitions={"success": "LEFT_RELEASE_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_RELEASE_1",
            PalGripperRelease(),
            transitions={"success": "LEFT_GO_TO_HANDLE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_GO_TO_HANDLE",
            FollowWaypointsFromCfg(),
            transitions={"success": "LEFT_GRASP", "fail": "fsm_fail"},
            remapping={
                "tag": "left_go_to_handle",
            },
        )
        smach.StateMachine.add(
            "LEFT_GRASP",
            PalGripperGrasp(),
            transitions={"success": "LEFT_TURN_HANDLE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_TURN_HANDLE",
            FollowWaypointsFromCfg(),
            transitions={"success": "BASE_VEL_CTRL_MODE", "fail": "fsm_fail"},
            remapping={
                "tag": "left_turn_handle",
            },
        )
        smach.StateMachine.add(
            "BASE_VEL_CTRL_MODE",
            ChangeTaskControlMode(),
            transitions={"success": "LEFT_GO_BACK", "fail": "fsm_fail"},
            remapping={
                "task_name": "base_task_name",
                "mode": "ctrl_mode_velocity",
            },
        )
        smach.StateMachine.add(
            "LEFT_GO_BACK",
            MoveToTargetFromCfg(),
            transitions={"success": "LEFT_CHANGE_BASE_LINK", "fail": "fsm_fail"},
            remapping={
                "tag": "left_go_back",
            },
        )
        smach.StateMachine.add(
            "LEFT_CHANGE_BASE_LINK",
            ChangeTaskBaseLink(),
            transitions={"success": "LEFT_RELEASE_2", "fail": "fsm_fail"},
            remapping={
                "task_name": "left_task_name",
                "task_base_link": "left_task_base_link",
            },
        )
        smach.StateMachine.add(
            "LEFT_RELEASE_2",
            PalGripperRelease(),
            transitions={"success": "BASE_GO_BACK", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "BASE_GO_BACK",
            MoveToTargetFromCfg(),
            transitions={"success": "LEFT_HOME_2", "fail": "fsm_fail"},
            remapping={
                "tag": "base_go_back",
            },
        )
        smach.StateMachine.add(
            "LEFT_HOME_2",
            MoveToTargetFromCfg(),
            transitions={"success": "BASE_POS_CTRL_MODE", "fail": "fsm_fail"},
            remapping={
                "tag": "left_home",
            },
        )
        smach.StateMachine.add(
            "BASE_POS_CTRL_MODE",
            ChangeTaskControlMode(),
            transitions={"success": "UPDATE_ODOM_2", "fail": "fsm_fail"},
            remapping={
                "task_name": "base_task_name",
                "mode": "ctrl_mode_position",
            },
        )
        smach.StateMachine.add(
            "UPDATE_ODOM_2",
            UpdateOdom(),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
        )

    # Execute the state machine
    outcome = sm.execute()


if __name__ == "__main__":
    main()
