#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from utils import set_custom_loggers
from states import (
    MoveToTargetFromCfg,
    FollowWaypointsFromCfg,
    PalGripperGrasp,
    PalGripperRelease,
    UpdateOdom,
)

import rospy
import rospkg
import smach
import tf2_ros


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Define parameters
    config_path = rospack.get_path("fsm_cartesio") + "/config/open_door_with_left.yaml"
    gripper_controller = "parallel_gripper_left_controller"

    # Create a SMACH state machine
    set_custom_loggers()
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])

    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "INIT_ODOM",
            UpdateOdom(client, tf_buffer),
            transitions={"success": "LEFT_HOME_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_HOME_1",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "left_home"),
            transitions={"success": "RIGHT_CAMERA_LOOK_FRONT", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_CAMERA_LOOK_FRONT",
            MoveToTargetFromCfg(
                client, tf_buffer, config_path, "right_camera_look_front"
            ),
            transitions={"success": "BASE_GO_TO_DOOR", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "BASE_GO_TO_DOOR",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "base_go_to_door"),
            transitions={"success": "UPDATE_ODOM_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "UPDATE_ODOM_1",
            UpdateOdom(client, tf_buffer),
            transitions={"success": "LEFT_RELEASE_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_RELEASE_1",
            PalGripperRelease(gripper_controller),
            transitions={"success": "LEFT_GO_TO_HANDLE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_GO_TO_HANDLE",
            FollowWaypointsFromCfg(client, tf_buffer, config_path, "left_go_to_handle"),
            transitions={"success": "LEFT_GRASP", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_GRASP",
            PalGripperGrasp(gripper_controller),
            transitions={"success": "LEFT_TURN_HANDLE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_TURN_HANDLE",
            FollowWaypointsFromCfg(client, tf_buffer, config_path, "left_turn_handle"),
            transitions={"success": "LEFT_GO_BACK", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_GO_BACK",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "left_go_back"),
            transitions={"success": "BASE_GO_BACK", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "BASE_GO_BACK",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "base_go_back"),
            transitions={"success": "LEFT_HOME_2", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "LEFT_HOME_2",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "left_home"),
            transitions={"success": "UPDATE_ODOM_2", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "UPDATE_ODOM_2",
            UpdateOdom(client, tf_buffer),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
        )

    # Execute the state machine
    sm.execute()


if __name__ == "__main__":
    main()
