#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from sm_factory import go_through_door

import rospkg
import rospy
import tf2_ros

import json

if __name__ == "__main__":

    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    file_folder_path = rospack.get_path("fsm_cartesio") + "/config/demo"
    config_path = rospack.get_path("fsm_cartesio") + f"/config/motions.yaml"

    # Wait for tf listener
    rospy.sleep(1)

    sm = go_through_door(
        "SUCCESS", "FAILURE", client, tf_buffer, config_path, file_folder_path
    )
    sm.execute()
