#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from states import (
    MoveToTargetFromCfg,
    FollowWaypointsFromCfg,
    PalGripperGrasp,
    PalGripperRelease,
    UpdateOdom,
    ChangeTaskControlMode,
    ChangeTaskBaseLink,
)
import numpy as np
import rospy
import rospkg
import smach
import tf2_ros


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Create a SMACH state machine
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])

    # Define userdata for the state machine
    sm.userdata.client = client
    sm.userdata.tf_buffer = tf_buffer
    sm.userdata.config_path = (
        rospack.get_path("fsm_cartesio") + "/config/pick_object.yaml"
    )
    sm.userdata.parallel_gripper_controller = "parallel_gripper_right_controller"
    sm.userdata.right_home_down = "right_home_down"
    sm.userdata.right_home_up = "right_home_up"
    sm.userdata.right_camera_look_table = "right_camera_look_table"
    sm.userdata.right_pick_mustard = "right_pick_mustard"


    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "INIT_ODOM",
            UpdateOdom(),
            transitions={"success": "RIGHT_RELEASE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_RELEASE",
            PalGripperRelease(),
            transitions={"success": "RIGHT_HOME_DOWN", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_HOME_DOWN",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_CAMERA_LOOK_TABLE", "fail": "fsm_fail"},
            remapping={
                "tag": "right_home_down",
            },
        )
        smach.StateMachine.add(
            "RIGHT_CAMERA_LOOK_TABLE",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_PICK_OBJECT", "fail": "fsm_fail"},
            remapping={
                "tag": "right_camera_look_table",
            },
        )
        smach.StateMachine.add(
            "RIGHT_PICK_OBJECT",
            FollowWaypointsFromCfg(),
            transitions={"success": "RIGHT_GRASP", "fail": "fsm_fail"},
            remapping={
                "tag": "right_pick_mustard",
            },
        )
        smach.StateMachine.add(
            "RIGHT_GRASP",
            PalGripperGrasp(),
            transitions={"success": "RIGHT_HOME_UP", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_HOME_UP",
            MoveToTargetFromCfg(),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
            remapping={
                "tag": "right_home_up",
            },
        )

    # Execute the state machine
    outcome = sm.execute()


if __name__ == "__main__":
    main()
