#!/usr/bin/env python

from cartesian_interface.pyci_all import *
from states import (
    ChangeTaskControlMode,
    ChangeTaskBaseLink,
    MoveToTargetFromCfg,
    FollowWaypointsFromCfg,
    PalGripperGrasp,
    PalGripperRelease,
    ParsePlan,
    UpdateOdom,
)
import numpy as np
import rospy
import rospkg
import smach
import tf2_ros


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Create a SMACH state machine
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])

    # Define userdata for the state machine
    sm.userdata.client = client
    sm.userdata.tf_buffer = tf_buffer
    sm.userdata.config_path = (
        rospack.get_path("fsm_cartesio") + "/config/pick_object.yaml"
    )
    sm.userdata.parallel_gripper_controller = "parallel_gripper_right_controller"
    sm.userdata.right_home = "right_home"
    sm.userdata.right_pre_manip_pose = "right_pre_manip_pose"
    sm.userdata.right_post_manip_pose = "right_post_manip_pose"

    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "PARSE_PLAN",
            ParsePlan(),
            transitions={"success": "INIT_ODOM", "fail": "fsm_fail"},
            remapping={
                "plan_srv_name": "whisper_llm",
                "pick_tag": "pick_tag",
            },
        )
        smach.StateMachine.add(
            "INIT_ODOM",
            UpdateOdom(),
            transitions={"success": "RIGHT_INIT_GRIPPER", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_INIT_GRIPPER",
            PalGripperRelease(),
            transitions={"success": "RIGHT_HOME_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_HOME_1",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_PRE_MANIP_1", "fail": "fsm_fail"},
            remapping={
                "tag": "right_home",
            },
        )
        smach.StateMachine.add(
            "RIGHT_PRE_MANIP_1",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_PICK_OBJECT", "fail": "fsm_fail"},
            remapping={
                "tag": "right_pre_manip_pose",
            },
        )
        smach.StateMachine.add(
            "RIGHT_PICK_OBJECT",
            FollowWaypointsFromCfg(),
            transitions={"success": "RIGHT_GRASP", "fail": "fsm_fail"},
            remapping={
                "tag": "pick_tag",
            },
        )
        smach.StateMachine.add(
            "RIGHT_GRASP",
            PalGripperGrasp(),
            transitions={"success": "RIGHT_POST_MANIP", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_POST_MANIP",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_HOME_2", "fail": "fsm_fail"},
            remapping={
                "tag": "right_post_manip_pose",
            },
        )
        smach.StateMachine.add(
            "RIGHT_HOME_2",
            MoveToTargetFromCfg(),
            transitions={"success": "RIGHT_RELEASE", "fail": "fsm_fail"},
            remapping={
                "tag": "right_home",
            },
        )
        smach.StateMachine.add(
            "RIGHT_RELEASE",
            PalGripperRelease(),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
        )

    # Execute the state machine
    outcome = sm.execute()


if __name__ == "__main__":
    main()
