#!/usr/bin/env python

from cartesian_interface.pyci_all import *\
from utils import set_custom_loggers
from states import (
    MoveToTargetFromCfg,
    FollowWaypointsFromCfg,
    PalGripperGrasp,
    PalGripperRelease,
    UpdateOdom,
)

import json
import rospy
import rospkg
import smach
import tf2_ros
from std_srvs.srv import Empty, EmptyRequest, Trigger, TriggerRequest


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Define parameters
    config_path = rospack.get_path("fsm_cartesio") + "/config/pick_object.yaml"
    gripper_controller = "parallel_gripper_right_controller"

    # Get request from LLM
    srv_proxy = rospy.ServiceProxy("whisper_llm", Trigger)
    req = TriggerRequest()
    res = srv_proxy(req)
    plan = json.loads(res.message)
    object_to_pick = plan["actions"]["object"]

    # Create a SMACH state machine
    set_custom_loggers()
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])


    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "INIT_ODOM",
            UpdateOdom(client, tf_buffer),
            transitions={"success": "RIGHT_INIT_GRIPPER", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_INIT_GRIPPER",
            PalGripperRelease(gripper_controller),
            transitions={"success": "RIGHT_HOME", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_HOME",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "right_home"),
            transitions={"success": "RIGHT_PRE_MANIP_1", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_PRE_MANIP",
            MoveToTargetFromCfg(client, tf_buffer, config_path, "right_pre_manip_pose"),
            transitions={"success": "RIGHT_PICK_OBJECT", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_PICK_OBJECT",
            FollowWaypointsFromCfg(client, tf_buffer, config_path, object_to_pick),
            transitions={"success": "RIGHT_GRASP", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_GRASP",
            PalGripperGrasp(gripper_controller),
            transitions={"success": "RIGHT_POST_MANIP", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_POST_MANIP",
            MoveToTargetFromCfg(
                client, tf_buffer, config_path, "right_post_manip_pose"
            ),
            transitions={"success": "RIGHT_RELEASE", "fail": "fsm_fail"},
        )
        smach.StateMachine.add(
            "RIGHT_RELEASE",
            PalGripperRelease(gripper_controller),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
        )

    # Execute the state machine
    sm.execute()


if __name__ == "__main__":
    main()
