#!/usr/bin/env python

from cartesian_interface.pyci_all import *\
from utils import set_custom_loggers
from states import (
    UpdateOdom,
)

import json
import rospy
import rospkg
import smach
import tf2_ros
from std_srvs.srv import Empty, EmptyRequest, Trigger, TriggerRequest


def main():
    rospy.init_node("open_door_smach_node")
    rospack = rospkg.RosPack()

    # Set up tf2 listener
    tf_buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(tf_buffer)

    # Init CartesI/O client
    client = pyci.CartesianInterfaceRos()

    # Wait for tf listener
    rospy.sleep(1)

    # Create a SMACH state machine
    set_custom_loggers()
    sm = smach.StateMachine(outcomes=["fsm_success", "fsm_fail"])


    # Open the state machine container
    with sm:
        smach.StateMachine.add(
            "UPDATE_ODOM",
            UpdateOdom(client, tf_buffer),
            transitions={"success": "fsm_success", "fail": "fsm_fail"},
        )

    # Execute the state machine
    sm.execute()


if __name__ == "__main__":
    main()
